spring.application.name=smartbudget-backend
spring.security.oauth2.resourceserver.jwt.issuer-uri=${COGNITO_ISSUER_URI}
aws.region=${AWS_REGION}
aws.s3.bucket=${S3_BUCKET_NAME}
openai.api-key=${OPENAI_API_KEY}
openai.model=gpt-5.6